json.id meal.id
json.user_id meal.user_id
json.name meal.name
json.meal_category meal.meal_category
json.calories meal.calories
json.protein meal.protein
json.fat meal.fat
json.carbs meal.carbs
json.upc_code meal.upc_code